"""Initial commit with consolidated schema

Revision ID: 65cf0ac31602
Revises: 
Create Date: 2025-07-20 13:39:28.998677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65cf0ac31602'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('password_change_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_uuid', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_chat_history_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_thinking_visible', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_uuid')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=False),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('asset_uuid')
    )
    op.create_index('ix_asset_project_id', 'assets', ['asset_project_id'], unique=False)
    op.create_index('ix_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_table('chat_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_uuid')
    )
    op.create_index('ix_chat_histories_chat_uuid', 'chat_histories', ['chat_uuid'], unique=True)
    op.create_index('ix_chat_histories_project_id', 'chat_histories', ['project_id'], unique=False)
    op.create_index('ix_chat_histories_timestamp', 'chat_histories', ['timestamp'], unique=False)
    op.create_index('ix_chat_histories_user_id', 'chat_histories', ['user_id'], unique=False)
    op.create_table('project_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='_user_project_uc')
    )
    op.create_table('chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_uuid', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_project_id', sa.Integer(), nullable=False),
    sa.Column('chunk_asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['chunk_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('chunk_uuid')
    )
    op.create_index('ix_chunk_asset_id', 'chunks', ['chunk_asset_id'], unique=False)
    op.create_index('ix_chunk_project_id', 'chunks', ['chunk_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_project_id', table_name='chunks')
    op.drop_index('ix_chunk_asset_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('project_access')
    op.drop_index('ix_chat_histories_user_id', table_name='chat_histories')
    op.drop_index('ix_chat_histories_timestamp', table_name='chat_histories')
    op.drop_index('ix_chat_histories_project_id', table_name='chat_histories')
    op.drop_index('ix_chat_histories_chat_uuid', table_name='chat_histories')
    op.drop_table('chat_histories')
    op.drop_index('ix_asset_type', table_name='assets')
    op.drop_index('ix_asset_project_id', table_name='assets')
    op.drop_table('assets')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
