"""add thinking column to chat_histories

Revision ID: ba6c24cb1a06
Revises: 65cf0ac31602
Create Date: 2025-08-05 12:20:41.320356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba6c24cb1a06'
down_revision: Union[str, None] = '65cf0ac31602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('thinking', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_histories', 'thinking')
    op.create_table('pgdata_proj2_asset5_sheet2',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj2_asset5_sheet2_pkey')
    )
    op.create_table('collection_384_5ad7b35d_3d79_4587_8007_c87db0cbe9a0',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_5ad7b35d_3d79_4587_8007_c87db0cbe9_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_5ad7b35d_3d79_4587_8007_c87db0cbe9a0_pkey')
    )
    op.create_table('pgdata_proj5_asset11_sheet2',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj5_asset11_sheet2_pkey')
    )
    op.create_table('collection_384_e33c7b6f_ea37_4003_ae9b_d768fb565255',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_e33c7b6f_ea37_4003_ae9b_d768fb5652_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_e33c7b6f_ea37_4003_ae9b_d768fb565255_pkey')
    )
    op.create_table('pgdata_proj4_asset9_sheet2',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj4_asset9_sheet2_pkey')
    )
    op.create_table('pgdata_proj4_asset9_sheet3',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj4_asset9_sheet3_pkey')
    )
    op.create_table('collection_384_06057126_8d63_4d18_878e_0e7f8d909c06',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_06057126_8d63_4d18_878e_0e7f8d909c_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_06057126_8d63_4d18_878e_0e7f8d909c06_pkey')
    )
    op.create_table('pgdata_proj5_asset11_sheet3',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj5_asset11_sheet3_pkey')
    )
    op.create_table('pgdata_proj2_asset5_sheet_2022',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj2_asset5_sheet_2022_pkey')
    )
    op.create_table('pgdata_proj4_asset9_sheet_2022',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj4_asset9_sheet_2022_pkey')
    )
    op.create_table('pgdata_proj2_asset5_sheet3',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj2_asset5_sheet3_pkey')
    )
    op.create_table('pgdata_proj5_asset11_sheet_2022',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj5_asset11_sheet_2022_pkey')
    )
    op.create_table('collection_384_177caa97_bf10_4c42_9a0d_c9ec3eb48a21',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_177caa97_bf10_4c42_9a0d_c9ec3eb48a_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_177caa97_bf10_4c42_9a0d_c9ec3eb48a21_pkey')
    )
    # ### end Alembic commands ###
