"""Add thinking visibility to projects

Revision ID: 8e8874782ebe
Revises: c4ce86f483d8
Create Date: 2025-07-10 17:57:41.357603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e8874782ebe'
down_revision: Union[str, None] = 'c4ce86f483d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pgdata_proj7_asset19_sheet2')
    op.drop_table('collection_384_8eb8ffa7_05a2_435b_b710_f7bdaf850d3a')
    op.drop_table('pgdata_proj7_asset19_sheet_2022')
    op.drop_table('pgdata_proj7_asset19_sheet3')
    op.add_column('projects', sa.Column('is_thinking_visible', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_thinking_visible')
    op.create_table('pgdata_proj7_asset19_sheet3',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj7_asset19_sheet3_pkey')
    )
    op.create_table('pgdata_proj7_asset19_sheet_2022',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj7_asset19_sheet_2022_pkey')
    )
    op.create_table('collection_384_8eb8ffa7_05a2_435b_b710_f7bdaf850d3a',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_8eb8ffa7_05a2_435b_b710_f7bdaf850d_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_8eb8ffa7_05a2_435b_b710_f7bdaf850d3a_pkey')
    )
    op.create_table('pgdata_proj7_asset19_sheet2',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj7_asset19_sheet2_pkey')
    )
    # ### end Alembic commands ###
