"""Add user_id to chat_histories for per-user chat

Revision ID: c4ce86f483d8
Revises: eb7b7acacdeb
Create Date: 2025-07-09 09:01:43.655730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ce86f483d8'
down_revision: Union[str, None] = 'eb7b7acacdeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_histories_user_id'), 'chat_histories', ['user_id'], unique=False)
    op.create_foreign_key('fk_chat_histories_user_id_users', 'chat_histories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chat_histories_user_id_users', 'chat_histories', type_='foreignkey')
    op.drop_index(op.f('ix_chat_histories_user_id'), table_name='chat_histories')
    op.drop_column('chat_histories', 'user_id')
    # ### end Alembic commands ###