"""Add project access control and chat history toggle

Revision ID: eb7b7acacdeb
Revises: 754e151caf21
Create Date: 2025-07-09 07:12:00.497327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb7b7acacdeb'
down_revision: Union[str, None] = '754e151caf21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='_user_project_uc')
    )
    op.drop_table('pgdata_proj4_asset10_sheet_2022')
    op.drop_table('pgdata_proj4_asset10_sheet3')
    op.drop_table('pgdata_proj5_asset13_sheet_2022')
    op.drop_table('pgdata_proj5_asset13_sheet2')
    op.drop_table('collection_384_4')
    op.drop_table('pgdata_proj5_asset16_sheet3')
    op.drop_table('pgdata_proj5_asset16_sheet2')
    op.drop_table('collection_384_f3669edf_45ec_45d7_97f0_425a7bd8a641')
    op.drop_table('pgdata_proj5_asset16_sheet_2022')
    op.drop_table('pgdata_proj4_asset10_sheet2')
    op.drop_table('pgdata_proj5_asset13_sheet3')
    op.add_column('projects', sa.Column('is_chat_history_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_chat_history_enabled')
    op.create_table('pgdata_proj5_asset13_sheet3',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj5_asset13_sheet3_pkey')
    )
    op.create_table('pgdata_proj4_asset10_sheet2',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj4_asset10_sheet2_pkey')
    )
    op.create_table('pgdata_proj5_asset16_sheet_2022',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj5_asset16_sheet_2022_pkey')
    )
    op.create_table('collection_384_f3669edf_45ec_45d7_97f0_425a7bd8a641',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_f3669edf_45ec_45d7_97f0_425a7bd8a6_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_f3669edf_45ec_45d7_97f0_425a7bd8a641_pkey')
    )
    op.create_table('pgdata_proj5_asset16_sheet2',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj5_asset16_sheet2_pkey')
    )
    op.create_table('pgdata_proj5_asset16_sheet3',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj5_asset16_sheet3_pkey')
    )
    op.create_table('collection_384_4',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name='collection_384_4_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_4_pkey')
    )
    op.create_table('pgdata_proj5_asset13_sheet2',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj5_asset13_sheet2_pkey')
    )
    op.create_table('pgdata_proj5_asset13_sheet_2022',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj5_asset13_sheet_2022_pkey')
    )
    op.create_table('pgdata_proj4_asset10_sheet3',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj4_asset10_sheet3_pkey')
    )
    op.create_table('pgdata_proj4_asset10_sheet_2022',
    sa.Column('pg_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lpt_100', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_retained_locally_80', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equalisation_fund', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discretionary_lpt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_revenue_budget_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lpt_self_funding__capital_budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_lpt_allocation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pg_id', name='pgdata_proj4_asset10_sheet_2022_pkey')
    )
    op.drop_table('project_access')
    # ### end Alembic commands ###
