"""create_chat_history_table_v2

Revision ID: f4c6edd1f9a9
Revises: 2b61584eb80c
Create Date: 2025-06-10 10:37:08.743750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid # Import uuid for default value


# revision identifiers, used by Alembic.
revision: str = 'f4c6edd1f9a9'
down_revision: Union[str, None] = '2b61584eb80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_uuid', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text("gen_random_uuid()")),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_histories_project_id'), 'chat_histories', ['project_id'], unique=False)
    op.create_index(op.f('ix_chat_histories_timestamp'), 'chat_histories', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_histories_chat_uuid'), 'chat_histories', ['chat_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_histories_chat_uuid'), table_name='chat_histories')
    op.drop_index(op.f('ix_chat_histories_timestamp'), table_name='chat_histories')
    op.drop_index(op.f('ix_chat_histories_project_id'), table_name='chat_histories')
    op.drop_table('chat_histories')
    # ### end Alembic commands ###